from geokernel import FType, Point


trait Curve:
    def point_at(self, t: FType) -> Point: ...
    def start_point(self) -> Point: ...
    def end_point(self) -> Point: ...
    def length(self) -> FType: ...
    def is_closed(self) -> Bool: ...
    def distance_to_point(self, p: Point) -> FType: ...
    def project_point(self, p: Point) -> Point: ...
