from geokernel import FType, Point


trait Curve:
    fn point_at(self, t: FType) -> Point: ...
    fn start_point(self) -> Point: ...
    fn end_point(self) -> Point: ...
    fn length(self) -> FType: ...
    fn is_closed(self) -> Bool: ...
