from geokernel import FType, Point, Vector3


trait Surface:
    fn point_at(self, u: FType, v: FType) -> Point: ...
    fn normal_at(self, u: FType, v: FType) -> Vector3: ...
    fn area(self) -> FType: ...
    fn is_planar(self) -> Bool: ...
