from geokernel import FType, Point, Vector3


trait Surface:
    def point_at(self, u: FType, v: FType) -> Point: ...
    def normal_at(self, u: FType, v: FType) -> Vector3: ...
    def area(self) -> FType: ...
    def is_planar(self) -> Bool: ...
